// SOURCE of the question pools (plain answers). Not served to players.
// Edit here, then run `npm run encode` to regenerate public/src/data/questions.js.

export const QUESTIONS = {
  school: [
    { question: "What is 7 × 8?", options: ["54", "56", "64", "48"], correctAnswer: 1 },
    { question: "What is the capital of France?", options: ["Paris", "Rome", "Berlin", "Madrid"], correctAnswer: 0 },
    { question: "How many sides does a hexagon have?", options: ["5", "8", "6", "7"], correctAnswer: 2 },
    { question: "Which planet is known as the Red Planet?", options: ["Venus", "Jupiter", "Saturn", "Mars"], correctAnswer: 3 },
    { question: "What sound does a duck make?", options: ["Moo", "Quack", "Oink", "Freedom"], correctAnswer: 1 },
    { question: "Water freezes at how many degrees Celsius?", options: ["0", "32", "100", "-10"], correctAnswer: 0 },
    { question: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], correctAnswer: 2 },
    { question: "What is 144 ÷ 12?", options: ["11", "14", "13", "12"], correctAnswer: 3 },
    { question: "Which gas do plants absorb from the air?", options: ["Oxygen", "Carbon dioxide", "Helium", "Nitrogen"], correctAnswer: 1 },
    { question: "How many continents are there?", options: ["5", "6", "7", "8"], correctAnswer: 2 },
    { question: "What do bees make?", options: ["Milk", "Honey", "Silk", "Ammo"], correctAnswer: 1 },
    { question: "What is the square root of 81?", options: ["9", "8", "7", "18"], correctAnswer: 0 },
    { question: "Who wrote 'Romeo and Juliet'?", options: ["Dickens", "Tolkien", "Shakespeare", "A duck"], correctAnswer: 2 },
    { question: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Ag", "Au"], correctAnswer: 3 },
    { question: "What is 15 + 27?", options: ["42", "41", "43", "32"], correctAnswer: 0 },
    { question: "How many days are in a leap year?", options: ["365", "366", "364", "360"], correctAnswer: 1 },
    { question: "How many legs does a spider have?", options: ["6", "8", "10", "12"], correctAnswer: 1 },
    { question: "What is the largest planet in our solar system?", options: ["Earth", "Saturn", "Jupiter", "Neptune"], correctAnswer: 2 },
    { question: "What is H2O?", options: ["Salt", "Water", "Oxygen", "Hydrogen"], correctAnswer: 1 },
    { question: "How many minutes are in an hour?", options: ["100", "30", "60", "90"], correctAnswer: 2 },
    { question: "Which shape has 3 sides?", options: ["Square", "Triangle", "Circle", "Pentagon"], correctAnswer: 1 },
    { question: "What is 9 × 9?", options: ["81", "72", "99", "89"], correctAnswer: 0 },
    { question: "Which of these animals is a mammal?", options: ["Shark", "Duck", "Dolphin", "Frog"], correctAnswer: 2 },
  ],

  police: [
    { question: "What does a red traffic light mean?", options: ["Go faster", "Stop", "Honk", "Quack"], correctAnswer: 1 },
    { question: "How many amendments does the U.S. Constitution have?", options: ["10", "27", "50", "2"], correctAnswer: 1 },
    { question: "Which amendment is about the right to bear arms?", options: ["First", "Fifth", "Second", "Tenth"], correctAnswer: 2 },
    { question: "What number do you call for emergencies in the U.S.?", options: ["911", "112", "999", "411"], correctAnswer: 0 },
    { question: "What does a yellow traffic light mean?", options: ["Speed up", "Prepare to stop", "Park", "Dance"], correctAnswer: 1 },
    { question: "The right to remain silent comes from which amendment?", options: ["Second", "Fourth", "Fifth", "Eighth"], correctAnswer: 2 },
    { question: "What do police officers wear on their chest?", options: ["A medal", "A badge", "A duck", "A clock"], correctAnswer: 1 },
    { question: "A 'jaywalker' is someone who...", options: ["Steals birds", "Crosses the street illegally", "Speeds", "Sings loudly"], correctAnswer: 1 },
    { question: "What is the speed limit usually in a U.S. school zone?", options: ["80 mph", "55 mph", "15–25 mph", "No limit"], correctAnswer: 2 },
    { question: "Which amendment protects freedom of speech?", options: ["First", "Second", "Third", "Ninth"], correctAnswer: 0 },
    { question: "What do you need to legally drive a car?", options: ["A hat", "A license", "A duck", "A trumpet"], correctAnswer: 1 },
    { question: "In the U.S., who can arrest a person?", options: ["A mailbox", "A police officer", "A pigeon", "A traffic cone"], correctAnswer: 1 },
    { question: "The Fourth Amendment protects against...", options: ["Bad weather", "Unreasonable searches", "Taxes", "Ducks"], correctAnswer: 1 },
    { question: "What does 'K-9 unit' refer to?", options: ["Police dogs", "Police boats", "Police ducks", "Speed cameras"], correctAnswer: 0 },
    { question: "What does DUI stand for?", options: ["Driving Under the Influence", "Duck Under Investigation", "Do Use Indicators", "Driving Using Internet"], correctAnswer: 0 },
    { question: "What do police use to measure a car's speed?", options: ["Radar gun", "Thermometer", "Compass", "Calendar"], correctAnswer: 0 },
    { question: "A police car flashes its lights behind you. You should...", options: ["Speed up", "Pull over safely", "Honk back", "Turn off your lights"], correctAnswer: 1 },
    { question: "A 'misdemeanor' is a...", options: ["Serious felony", "Minor crime", "Parking spot", "Court building"], correctAnswer: 1 },
    { question: "In a U.S. jury trial, who decides guilt?", options: ["The police", "The jury", "The lawyer", "The duck"], correctAnswer: 1 },
    { question: "What is bail?", options: ["A prison meal", "Money paid to be released before trial", "A police car", "A type of badge"], correctAnswer: 1 },
    { question: "Miranda rights are read when someone is...", options: ["Arrested", "Hired", "Married", "Promoted"], correctAnswer: 0 },
    { question: "What does a U.S. stop sign look like?", options: ["Red octagon", "Yellow triangle", "Blue circle", "Green square"], correctAnswer: 0 },
    { question: "Which amendment bans cruel and unusual punishment?", options: ["Second", "Fifth", "Eighth", "First"], correctAnswer: 2 },
  ],

  president: [
    { question: "How many years is a U.S. presidential term?", options: ["2", "4", "6", "8"], correctAnswer: 1 },
    { question: "Where does the U.S. President live?", options: ["The Pentagon", "The White House", "Capitol Hill", "A duck pond"], correctAnswer: 1 },
    { question: "How many U.S. states are there?", options: ["48", "50", "52", "51"], correctAnswer: 1 },
    { question: "Who was the first U.S. President?", options: ["Abraham Lincoln", "Thomas Jefferson", "George Washington", "John Adams"], correctAnswer: 2 },
    { question: "How many senators does each state have?", options: ["1", "2", "4", "Depends on population"], correctAnswer: 1 },
    { question: "How many times can a person be elected U.S. President?", options: ["1", "2", "3", "Unlimited"], correctAnswer: 1 },
    { question: "What is the minimum age to be U.S. President?", options: ["30", "35", "40", "45"], correctAnswer: 1 },
    { question: "What is the President's plane usually called?", options: ["Air Force One", "Eagle One", "Sky Chief", "Duck Force One"], correctAnswer: 0 },
    { question: "Which branch of government makes federal laws?", options: ["Executive", "Judicial", "Legislative", "Military"], correctAnswer: 2 },
    { question: "Who is Commander in Chief of the U.S. military?", options: ["The President", "Secretary of Defense", "A general", "The Speaker"], correctAnswer: 0 },
    { question: "How many justices sit on the U.S. Supreme Court?", options: ["7", "9", "11", "12"], correctAnswer: 1 },
    { question: "Which agency protects the President?", options: ["FBI", "NASA", "Secret Service", "Post Office"], correctAnswer: 2 },
    { question: "What city is the U.S. capital?", options: ["New York", "Washington, D.C.", "Philadelphia", "Boston"], correctAnswer: 1 },
    { question: "In what year was the Declaration of Independence signed?", options: ["1776", "1789", "1812", "1492"], correctAnswer: 0 },
    { question: "Who can veto a bill passed by Congress?", options: ["The President", "The Supreme Court", "The Senate", "Governors"], correctAnswer: 0 },
    { question: "How many voting members are in the House of Representatives?", options: ["100", "435", "538", "250"], correctAnswer: 1 },
    { question: "How many electoral votes are needed to win the presidency?", options: ["270", "300", "218", "51"], correctAnswer: 0 },
    { question: "What is the President's office called?", options: ["Round Office", "Oval Office", "Square Office", "Duck Office"], correctAnswer: 1 },
    { question: "On which date is U.S. Independence Day?", options: ["July 4", "June 14", "November 11", "January 1"], correctAnswer: 0 },
    { question: "Who wrote most of the Declaration of Independence?", options: ["Benjamin Franklin", "Thomas Jefferson", "George Washington", "Alexander Hamilton"], correctAnswer: 1 },
    { question: "Which president is on the U.S. $1 bill?", options: ["Lincoln", "Washington", "Jefferson", "Jackson"], correctAnswer: 1 },
    { question: "Which president is on the U.S. penny?", options: ["Lincoln", "Washington", "Roosevelt", "Kennedy"], correctAnswer: 0 },
    { question: "What is the national bird of the United States?", options: ["Duck", "Bald eagle", "Turkey", "Pigeon"], correctAnswer: 1 },
    { question: "Where does the U.S. Congress meet?", options: ["The Capitol", "The White House", "The Pentagon", "Wall Street"], correctAnswer: 0 },
    { question: "Who becomes President if the President can no longer serve?", options: ["The Speaker", "The Vice President", "The Chief Justice", "The oldest senator"], correctAnswer: 1 },
    { question: "Which branch of government includes the courts?", options: ["Legislative", "Executive", "Judicial", "Electoral"], correctAnswer: 2 },
  ],
};
