// SOURCE of the question pools (plain answers). Not served to players.
// Edit here, then run `npm run encode` to regenerate public/src/data/questions.js.
//
// Nội dung: Giáo trình Chủ nghĩa xã hội khoa học, Chương 4 (mục I và III.1) - Chủ đề 3 về dân chủ.
//   school    (Màn 1): DỄ         - 15 câu - ý chính được nói thẳng trong sách
//   police    (Màn 2): TRUNG BÌNH - 15 câu - chi tiết nhỏ, ít người để ý trong đoạn văn
//   president (Màn 3): KHÓ        - 30 câu - phải suy luận / vận dụng ý chính, nhiều câu bẫy
// Đáp án đúng luôn đặt ở vị trí 0 cho dễ soát; game tự xáo thứ tự khi hiển thị.
// Các phương án được viết dài ngắn tương đương để không đoán được theo độ dài.

const q = (question, correct, ...wrong) => ({ question, options: [correct, ...wrong], correctAnswer: 0 });

export const QUESTIONS = {
  // ---------------------------------------------------------------- DỄ
  school: [
    q('Theo nghĩa gốc của các nhà tư tưởng Hy Lạp cổ đại, dân chủ là gì?',
      'Nhân dân cai trị', 'Nhân dân được bảo vệ', 'Nhân dân được tự do', 'Nhân dân bầu ra vua'),
    q('Về phương diện quyền lực, chủ nghĩa Mác - Lênin cho rằng dân chủ là gì?',
      'Quyền lực thuộc về nhân dân', 'Quyền lực thuộc về nhà nước', 'Quyền lực thuộc về đa số', 'Quyền lực thuộc về pháp luật'),
    q('Trên phương diện tổ chức và quản lý xã hội, dân chủ là gì?',
      'Một nguyên tắc', 'Một hình thái nhà nước', 'Một giá trị nhân loại', 'Một chế độ chính trị'),
    q('Chủ tịch Hồ Chí Minh khẳng định: dân chủ là...',
      'Dân là chủ và dân làm chủ', 'Dân là gốc và dân là chủ', 'Dân được biết và được bàn', 'Dân làm chủ và dân hưởng thụ'),
    q('Trong ba nền dân chủ đã có trong lịch sử, nền dân chủ nào gắn với chế độ tư bản chủ nghĩa?',
      'Dân chủ tư sản', 'Dân chủ chủ nô', 'Dân chủ vô sản', 'Dân chủ nguyên thủy'),
    q('Nền dân chủ xã hội chủ nghĩa chính thức được xác lập sau sự kiện nào?',
      'Cách mạng Tháng Mười Nga 1917', 'Công xã Pari ở nước Pháp năm 1871', 'Cách mạng Tháng Tám 1945', 'Cách mạng tư sản Pháp 1789'),
    q('Nền dân chủ xã hội chủ nghĩa còn được gọi là gì?',
      'Dân chủ vô sản', 'Dân chủ nhân dân', 'Dân chủ tập thể', 'Dân chủ công nông'),
    q('Theo V.I. Lênin, chế độ dân chủ vô sản so với bất cứ chế độ dân chủ tư sản nào cũng dân chủ hơn...',
      'gấp triệu lần', 'gấp nghìn lần', 'gấp trăm lần', 'gấp vạn lần'),
    q('Bản chất kinh tế của nền dân chủ xã hội chủ nghĩa dựa trên chế độ sở hữu nào?',
      'Công hữu về tư liệu sản xuất chủ yếu', 'Tư hữu về tư liệu sản xuất chủ yếu', 'Sở hữu hỗn hợp giữa nhà nước và tư nhân', 'Sở hữu tập thể về mọi tài sản'),
    q('Mục tiêu tổng quát của cách mạng Việt Nam: "..., nước mạnh, dân chủ, công bằng, văn minh".',
      'Dân giàu', 'Dân vui', 'Dân yên', 'Dân khỏe'),
    q('Đảng khẳng định dân chủ xã hội chủ nghĩa là bản chất của chế độ ta, vừa là mục tiêu, vừa là...',
      'động lực', 'phương tiện', 'điều kiện', 'nền tảng'),
    q('Bản chất dân chủ xã hội chủ nghĩa ở Việt Nam được thực hiện qua những hình thức nào?',
      'Trực tiếp và gián tiếp', 'Tập trung và phân tán', 'Đại diện và ủy quyền', 'Cơ sở và trung ương'),
    q('Quốc hội nước ta hoạt động theo nhiệm kỳ bao nhiêu năm?',
      '5 năm', '4 năm', '6 năm', '3 năm'),
    q('Phương châm của các quy chế dân chủ: "Dân biết, dân ..., dân làm, dân kiểm tra".',
      'bàn', 'hỏi', 'nghe', 'theo'),
    q('Đại hội VI (1986) khẳng định trong toàn bộ hoạt động, Đảng phải quán triệt tư tưởng nào?',
      '"Lấy dân làm gốc"', '"Lấy dân làm chủ"', '"Lấy dân làm đầu"', '"Lấy dân làm trọng"'),
  ],

  // ---------------------------------------------------------- TRUNG BÌNH
  police: [
    q('Trong nền dân chủ chủ nô, ngoài giai cấp chủ nô, những ai còn được tính là "dân"?',
      'Tăng lữ, thương gia và một số trí thức',
      'Binh lính, nông dân và thợ thủ công',
      'Quan lại, địa chủ và các thương nhân giàu',
      'Nô lệ đã được giải phóng và con cái'),
    q('Trong "Đại hội nhân dân" thời nguyên thủy, mọi người tham gia quyết định bằng cách nào?',
      'Giơ tay hoặc hoan hô', 'Bỏ phiếu kín bằng đá', 'Rút thăm ngẫu nhiên', 'Để bô lão quyết định'),
    q('Dưới chế độ chuyên chế phong kiến, sự thống trị của giai cấp được "khoác lên chiếc áo" gì?',
      'Thần bí của thế lực siêu nhiên',
      'Pháp lý của nhà nước cộng hòa',
      'Đạo đức của các bậc hiền triết',
      'Dân chủ của các hội đồng làng'),
    q('Sau Cách mạng Tháng Mười, nhân dân lao động ở nhiều nước đã thiết lập nhà nước gì?',
      'Nhà nước công - nông', 'Nhà nước công - binh', 'Nhà nước nông - binh', 'Nhà nước toàn dân'),
    q('V.I. Lênin gọi sự lãnh đạo của giai cấp công nhân thông qua Đảng đối với toàn xã hội về mọi mặt là gì?',
      'Sự thống trị chính trị', 'Sự thống nhất chính trị', 'Sự lãnh đạo toàn diện', 'Sự chuyên chính toàn diện'),
    q('Khi nhân dân tham gia ngày càng đông vào quản lý và dân chủ thành thói quen, giáo trình gọi đó là...',
      'xã hội tự quản', 'xã hội pháp quyền', 'xã hội công dân', 'xã hội hài hòa'),
    q('Theo chủ nghĩa Mác - Lênin, giai cấp vô sản không thể hoàn thành cách mạng xã hội chủ nghĩa nếu không được chuẩn bị thông qua...',
      'cuộc đấu tranh cho dân chủ', 'cuộc đấu tranh kinh tế', 'cuộc cải cách ruộng đất triệt để', 'cuộc cách mạng văn hóa'),
    q('Dân chủ xã hội chủ nghĩa kế thừa có chọn lọc giá trị của các nền dân chủ trước đó, "trước hết là"...',
      'nền dân chủ tư sản', 'nền dân chủ chủ nô', 'nền dân chủ nguyên thủy', 'nền dân chủ nhân dân'),
    q('Dưới góc độ tư tưởng - văn hóa, giáo trình coi dân chủ là gì?',
      'Một thành tựu văn hóa, một quá trình sáng tạo văn hóa',
      'Một thiết chế chính trị, một bộ máy của nhà nước',
      'Một chuẩn mực đạo đức, một lối sống của cộng đồng',
      'Một quyền pháp lý, một nghĩa vụ của mỗi người công dân'),
    q('Trước đổi mới, những lĩnh vực nào liên quan mật thiết đến dân chủ xã hội chủ nghĩa "chưa được đặt đúng vị trí"?',
      'Dân sinh, dân trí, dân quyền', 'Dân tộc, dân chủ, dân sinh', 'Dân cư, dân số, dân trí', 'Dân quyền, dân tộc, dân vận'),
    q('Trong hệ thống chính trị xã hội chủ nghĩa, Đảng ta xem Nhà nước là gì?',
      '"Trụ cột", "một công cụ chủ yếu, vững mạnh"',
      '"Hạt nhân", "lực lượng lãnh đạo xã hội"',
      '"Nền tảng", "cơ sở chính trị của chế độ"',
      '"Cầu nối", "chỗ dựa vững chắc của nhân dân"'),
    q('Theo Hồ Chí Minh, trong Tổng tuyển cử 1946, "hễ là những người muốn lo việc nước thì đều có quyền..."',
      'ra ứng cử', 'đi bầu cử', 'góp ý kiến', 'làm cán bộ'),
    q('Đại hội VI: "ở đâu nhân dân lao động có ý thức làm chủ và được làm chủ thật sự, thì ở đấy xuất hiện..."',
      'phong trào cách mạng', 'sức mạnh đoàn kết', 'nền dân chủ thực sự', 'sự phát triển mạnh'),
    q('Theo giáo trình, chủ nghĩa xã hội không thể duy trì và thắng lợi nếu không...',
      'thực hiện đầy đủ dân chủ', 'xây dựng kinh tế vững mạnh', 'có hệ thống pháp luật đủ', 'có nhà nước pháp quyền'),
    q('Nền dân chủ xã hội chủ nghĩa "ra sức động viên, thu hút" điều gì của nhân dân?',
      'Mọi tiềm năng sáng tạo, tính tích cực xã hội',
      'Mọi nguồn lực vật chất, tài chính sẵn có',
      'Mọi ý kiến phản biện đối với chủ trương, chính sách',
      'Mọi lực lượng lao động trong sản xuất'),
  ],

  // ----------------------------------------------------------------- KHÓ
  president: [
    q('Nhận định "Dân chủ sẽ mất đi khi nhà nước tiêu vong" được đánh giá thế nào theo giáo trình?',
      'Chỉ đúng với dân chủ là một hình thức nhà nước',
      'Đúng với mọi cách hiểu khác nhau về dân chủ',
      'Sai hoàn toàn, vì dân chủ tồn tại mãi mãi với con người',
      'Chỉ đúng với dân chủ là một giá trị xã hội'),
    q('Ý kiến "Việt Nam không đi theo con đường tư bản chủ nghĩa nên không có dân chủ thực sự" sai ở tiền đề nào?',
      'Đồng nhất dân chủ nói chung với dân chủ tư sản',
      'Cho rằng dân chủ cần được pháp luật thừa nhận và bảo đảm',
      'Cho rằng dân chủ gắn với một chế độ xã hội',
      'Cho rằng dân chủ là quyền lực của nhân dân'),
    q('Theo giáo trình, tiêu chí quyết định để biết một nền dân chủ có "thực sự" hay không là gì?',
      'Dân là ai và bản chất chế độ xã hội đó ra sao',
      'Có bao nhiêu đảng chính trị tham gia tranh cử',
      'Mức thu nhập bình quân đầu người của quốc gia',
      'Nhà nước theo chính thể cộng hòa hay quân chủ'),
    q('Đợt lấy ý kiến nhân dân về dự thảo sửa đổi Hiến pháp thể hiện rõ nhất nội dung dân chủ nào?',
      'Nhân dân tham gia xây dựng chính sách, pháp luật',
      'Nhân dân làm chủ các tư liệu sản xuất chủ yếu',
      'Nhân dân hưởng thụ các giá trị văn hóa tinh thần',
      'Nhân dân ủy quyền để Quốc hội quyết định thay'),
    q('Người dân phản ánh sai phạm qua mạng xã hội, buộc chính quyền địa phương phải xử lý. Đây là biểu hiện của...',
      'dân chủ trực tiếp - kiểm tra, giám sát',
      'dân chủ gián tiếp - ủy quyền đại diện',
      'dân chủ kinh tế - làm chủ sản xuất',
      'dân chủ nội bộ trong tổ chức chính trị'),
    q('Cử tri bầu ra đại biểu, rồi Quốc hội thông qua Luật Đất đai. Việc Quốc hội thông qua luật thuộc hình thức nào?',
      'Dân chủ gián tiếp', 'Dân chủ trực tiếp', 'Dân chủ cơ sở', 'Dân chủ tự quản'),
    q('Vì sao đem mức độ dân chủ hiện nay của các nước xã hội chủ nghĩa so ngang với các nước tư bản phát triển là chưa thỏa đáng?',
      'Hai bên khác nhau về thời gian hình thành và xuất phát điểm',
      'Hai nền dân chủ đó có cùng một bản chất giai cấp như nhau',
      'Các nước tư bản đã không còn điều chỉnh gì về mặt xã hội',
      'Dân chủ xã hội chủ nghĩa không kế thừa gì từ dân chủ tư sản'),
    q('Từ luận điểm "dân chủ trên lĩnh vực kinh tế là cơ sở", có thể suy ra điều gì?',
      'Thiếu dân chủ kinh tế thì dân chủ chính trị khó bền vững',
      'Chỉ cần kinh tế tăng trưởng nhanh là đã có đủ mọi dân chủ',
      'Dân chủ chính trị không hề ảnh hưởng tới kinh tế',
      'Dân chủ kinh tế chỉ là hệ quả của dân chủ chính trị'),
    q('Nếu dân chủ không đi đôi với kỷ luật, kỷ cương và không được pháp luật bảo đảm, có thể suy ra hệ quả gì?',
      'Dân chủ dễ trở nên tùy tiện, vô tổ chức',
      'Dân chủ sẽ được mở rộng nhanh và bền hơn',
      'Quyền lực sẽ tự động về tay toàn dân',
      'Nhà nước sẽ tiêu vong sớm hơn dự kiến'),
    q('Theo lập luận của giáo trình, vì sao dân chủ tư sản dù tiến bộ vẫn là dân chủ của thiểu số?',
      'Quyền lực gắn với thiểu số nắm tư liệu sản xuất',
      'Số người được đi bầu cử ở các nước đó còn rất ít',
      'Pháp luật tư sản không thừa nhận quyền con người',
      'Nhà nước tư sản không tổ chức bầu cử định kỳ'),
    q('"Dân chủ vô sản loại bỏ quyền dân chủ của các giai cấp là đối tượng của nhà nước vô sản". Suy ra nhận định nào hợp lý?',
      'Dân chủ XHCN không phải là dân chủ cho tất cả mọi người',
      'Dân chủ XHCN là thứ dân chủ thuần túy, phi giai cấp',
      'Dân chủ XHCN bảo đảm quyền như nhau cho mọi giai cấp',
      'Dân chủ XHCN là dân chủ chỉ dành riêng cho đảng viên'),
    q('Khi dân chủ đã trở thành "thói quen, tập quán" trong sinh hoạt xã hội, dân chủ mất đi tính chất gì?',
      'Tính chính trị', 'Tính nhân dân', 'Tính dân tộc', 'Tính nhân loại'),
    q('Vì sao giáo trình coi sự lãnh đạo của Đảng Cộng sản là yếu tố bảo đảm quyền lực thực sự thuộc về nhân dân?',
      'Đảng đại biểu cho trí tuệ, lợi ích của công nhân, nhân dân và dân tộc',
      'Đảng trực tiếp thay nhân dân quyết định mọi công việc của bộ máy nhà nước',
      'Đảng là tổ chức có số lượng thành viên đông nhất trong toàn xã hội',
      'Đảng là cơ quan quyền lực nhà nước cao nhất theo quy định của luật'),
    q('Có ý kiến: "Dân chủ xã hội chủ nghĩa phủ định hoàn toàn dân chủ tư sản". Theo giáo trình, ý kiến này...',
      'Sai, vì dân chủ XHCN kế thừa có chọn lọc dân chủ tư sản',
      'Đúng, vì hai nền dân chủ khác nhau hoàn toàn về bản chất',
      'Đúng, vì dân chủ tư sản không có giá trị tiến bộ nào cả',
      'Sai, vì hai nền dân chủ có cùng bản chất giai cấp với nhau'),
    q('Đảng làm cho phong trào quần chúng có tính tự giác cao trong xây dựng dân chủ chủ yếu bằng cách nào?',
      'Đưa chủ nghĩa Mác - Lênin vào quần chúng, nâng cao giác ngộ',
      'Trực tiếp tổ chức bầu cử và kiểm phiếu ở mọi cấp chính quyền',
      'Thay nhân dân quản lý toàn bộ công việc của bộ máy nhà nước',
      'Ban hành toàn bộ hệ thống pháp luật thay cho Quốc hội'),
    q('Vì sao "có nhiều đảng cạnh tranh" không phải là tiêu chí quyết định của dân chủ thực sự theo giáo trình?',
      'Vì bản chất dân chủ do giai cấp lãnh đạo và chế độ xã hội quyết định',
      'Vì ở các nước đa đảng hoàn toàn không có bầu cử tự do nào',
      'Vì chế độ đa đảng chỉ tồn tại trong xã hội chiếm hữu nô lệ và phong kiến',
      'Vì dân chủ XHCN không cần đến sự lãnh đạo của đảng nào cả'),
    q('Tình huống: xã ban hành quy định ảnh hưởng tới dân nhưng không công khai. Khâu nào trong phương châm bị vi phạm trước tiên?',
      '"Dân biết"', '"Dân bàn"', '"Dân làm"', '"Dân kiểm tra"'),
    q('Tình huống: thôn họp để người dân thảo luận và thống nhất phương án làm đường. Đây chủ yếu là khâu nào?',
      '"Dân bàn"', '"Dân biết"', '"Dân làm"', '"Dân kiểm tra"'),
    q('Vì sao phát huy dân chủ được coi là "động lực" phát triển đất nước?',
      'Vì phát huy được sức mạnh, sự sáng tạo của toàn dân tộc',
      'Vì làm giảm bớt vai trò quản lý xã hội của nhà nước',
      'Vì thay thế được hoàn toàn cơ chế thị trường hiện nay',
      'Vì loại bỏ được mọi mâu thuẫn còn tồn tại trong xã hội'),
    q('Theo giáo trình, dân chủ trong xã hội và trong đời sống văn hóa - tinh thần do yếu tố nào quy định và quyết định?',
      'Dân chủ trong kinh tế và chính trị',
      'Trình độ học vấn của từng cá nhân',
      'Truyền thống văn hóa của địa phương',
      'Mức độ hội nhập quốc tế của đất nước'),
    q('Chính sách nào thể hiện đúng nhất bản chất kinh tế của nền dân chủ xã hội chủ nghĩa?',
      'Phân phối chủ yếu theo kết quả lao động',
      'Phân phối chủ yếu theo mức vốn góp',
      'Phân phối bình quân như nhau cho mọi người dân',
      'Phân phối hoàn toàn theo nhu cầu'),
    q('Dân chủ XHCN là "đỉnh cao trong lịch sử tiến hóa của dân chủ" nhưng hiện còn nhiều hạn chế. Cách hiểu nào hợp lý?',
      'Đỉnh cao về bản chất, còn đang hoàn thiện về mức độ',
      'Đã hoàn thiện tuyệt đối cả về bản chất lẫn mức độ',
      'Thấp hơn dân chủ tư sản cả về bản chất lẫn mức độ',
      'Chỉ là đỉnh cao trên lý thuyết, không có trong thực tế'),
    q('Hai nhận định: (1) Dân chủ là một giá trị nhân loại chung; (2) Dân chủ là hình thức nhà nước của giai cấp cầm quyền. Theo giáo trình...',
      'Cả hai đều đúng, xét ở hai phương diện khác nhau',
      'Chỉ (1) đúng, vì dân chủ không mang tính giai cấp',
      'Chỉ (2) đúng, vì dân chủ không phải giá trị chung',
      'Cả hai đều sai theo quan điểm Mác - Lênin'),
    q('Nhà nước pháp quyền "thượng tôn pháp luật". Liên hệ với dân chủ, điều này có nghĩa là gì?',
      'Quyền làm chủ của dân được pháp luật ghi nhận và bảo đảm',
      'Pháp luật đứng trên và hạn chế quyền làm chủ của người dân',
      'Nhà nước đứng trên pháp luật để bảo vệ nhân dân',
      'Nhân dân không cần tham gia vào việc xây dựng luật'),
    q('Từ nguyên tắc "quyền lực nhà nước là thống nhất, có phân công, phối hợp và kiểm soát", nhận định nào đúng?',
      'Các cơ quan có chức năng riêng nhưng cùng thực hiện quyền lực của nhân dân',
      'Ba nhánh lập pháp, hành pháp, tư pháp hoàn toàn độc lập và đối trọng với nhau',
      'Mọi quyền lực nhà nước được tập trung vào một cơ quan duy nhất',
      'Các cơ quan nhà nước không cần kiểm soát lẫn nhau khi đã thống nhất'),
    q('Giáo trình nói dân chủ là "sản phẩm và thành quả của quá trình đấu tranh giai cấp". Điều này có nghĩa là...',
      'dân chủ gắn với cuộc đấu tranh vì giá trị tiến bộ của các giai cấp',
      'dân chủ chỉ có thể xuất hiện khi xã hội đã hoàn toàn không còn giai cấp',
      'dân chủ do các nhà tư tưởng tự nghĩ ra rồi áp dụng vào',
      'dân chủ là thứ có sẵn trong bản tính tự nhiên của con người'),
    q('Phát biểu nào SAI về dân chủ xã hội chủ nghĩa ở Việt Nam theo giáo trình?',
      'Chỉ được thực hiện qua dân chủ đại diện ở Quốc hội',
      'Dựa vào Nhà nước XHCN và sự ủng hộ của nhân dân',
      'Thể hiện ở cả kinh tế, chính trị, văn hóa, xã hội',
      'Gắn với kỷ luật, kỷ cương và được pháp luật bảo đảm'),
    q('Giáo trình nêu việc xây dựng dân chủ XHCN ở Việt Nam gặp khó khăn. Điều nào KHÔNG thuộc các khó khăn đó?',
      'Thiếu một hệ tư tưởng dẫn đường cho cách mạng',
      'Xuất phát từ một nền kinh tế kém phát triển',
      'Chịu hậu quả chiến tranh tàn phá nặng nề',
      'Tiêu cực xã hội chưa được khắc phục triệt để'),
    q('Câu nói của Hồ Chí Minh "Chính quyền từ xã đến Chính phủ trung ương do dân cử ra" gắn trực tiếp nhất với hình thức nào?',
      'Dân chủ gián tiếp', 'Dân chủ trực tiếp', 'Dân chủ cơ sở', 'Dân chủ nội bộ'),
    q('Dân chủ XHCN "chỉ có được với điều kiện tiên quyết là bảo đảm vai trò lãnh đạo duy nhất của Đảng". Suy ra nhận định nào?',
      'Dân chủ XHCN mang tính nhất nguyên về chính trị',
      'Dân chủ XHCN đòi hỏi sự cạnh tranh của nhiều đảng',
      'Dân chủ XHCN có thể tồn tại mà không cần nhà nước',
      'Dân chủ XHCN chỉ là dân chủ trong nội bộ của Đảng'),
  ],
};
